In [1]:
import pandas as pd
import numpy as np

In [71]:
data = pd.read_csv('checkins.dat', sep = '|', skipinitialspace=True).dropna()
data.columns = data.columns.str.strip()
data.drop(columns=['id', 'user_id', 'venue_id', 'created_at'], inplace=True)

data.columns

Index(['latitude', 'longitude'], dtype='object')

In [72]:
data.head()

latitude   longitude
2   38.895112  -77.036366
4   33.800745  -84.410520
8   45.523452 -122.676207
10  40.764462 -111.904565
11  33.448377 -112.074037

In [73]:
train = data.head(n=100000)

In [74]:
from sklearn.cluster import MeanShift
model = MeanShift(bandwidth=0.1)
model.fit(train)

MeanShift(bandwidth=0.1, bin_seeding=False, cluster_all=True, min_bin_freq=1,
          n_jobs=None, seeds=None)

In [79]:
centers = model.cluster_centers_
print(centers)
print(centers.shape)

[[  40.7177164   -73.99183542]
 [  33.44943805 -112.00213969]
 [  33.44638027 -111.90188756]
 ...
 [ -37.8229826   145.1811902 ]
 [ -41.2924945   174.7732353 ]
 [ -45.0311622   168.6626435 ]]
(3231, 2)


In [80]:
office_coord = pd.DataFrame(data=
                            [[33.751277, -118.188740],
                             [25.867736, -80.324116],
                             [51.503016, -0.075479],
                             [52.378894, 4.885084],
                             [39.366487, 117.036146],
                             [-33.868457, 151.205134]],
                            columns=['latitude', 'longitude']
                           )

In [96]:
from scipy.spatial.distance import cdist
distances = cdist(centers, office_coord)

In [97]:
distances

array([[ 44.74257092,  16.14371999,  74.69906582,  79.73425538,
        191.0327603 , 237.22725876],
       [  6.19395917,  32.5726786 , 113.37331719, 118.41008135,
        229.11470442, 271.67953165],
       [  6.29424146,  32.47447468, 113.2748328 , 118.31160891,
        229.01456477, 271.58164907],
       ...,
       [272.92232369, 234.32701671, 170.52458466, 166.79141452,
         82.16056067,   7.20598166],
       [302.42071128, 263.78998313, 197.94716381, 194.00080664,
         99.19396543,  24.70974973],
       [297.47334157, 258.88426019, 194.40010686, 190.55657439,
         98.93562773,  20.72126023]])

In [102]:
print(np.unravel_index(np.argmin(distances, axis=None), distances.shape))

(420, 5)


In [104]:
centers[420]

array([-33.86063043, 151.20477593])